
/* Drop Tables */

DROP TABLE QAALBABOARD CASCADE CONSTRAINTS;
DROP TABLE CAREER CASCADE CONSTRAINTS;
DROP TABLE HIRE_RESUME CASCADE CONSTRAINTS;
DROP TABLE RESUME_HIRE CASCADE CONSTRAINTS;
DROP TABLE RESUME_LIST CASCADE CONSTRAINTS;
DROP TABLE RESUME CASCADE CONSTRAINTS;
DROP TABLE ALBA CASCADE CONSTRAINTS;
DROP TABLE COMMON CASCADE CONSTRAINTS;
DROP TABLE HIRE CASCADE CONSTRAINTS;
DROP TABLE QACOMBOARD CASCADE CONSTRAINTS;
DROP TABLE COMPANY CASCADE CONSTRAINTS;
DROP TABLE GUIDE CASCADE CONSTRAINTS;
DROP TABLE NOTICE CASCADE CONSTRAINTS;
DROP TABLE MANAGER CASCADE CONSTRAINTS;




/* Create Tables */

CREATE TABLE ALBA
(
	ALBA_ID varchar2(20) NOT NULL,
	ALBA_PASSWORD varchar2(30) NOT NULL,
	ALBA_BIR date,
	ALBA_NAME varchar2(15) NOT NULL,
	ALBA_SEXDSTN number(1) NOT NULL,
	ALBA_MAIL varchar2(50) NOT NULL,
	ALBA_TEL varchar2(15) NOT NULL,
	ALBA_ADD varchar2(100) NOT NULL,
	ALBA_AUTH number(1) NOT NULL,
	PRIMARY KEY (ALBA_ID)
);


CREATE TABLE CAREER
(
	CR_NUM number(5) NOT NULL,
	CR_COM_NAME varchar2(50) NOT NULL,
	CR_COM_TERM varchar2(25) NOT NULL,
	CR_COM_TASK varchar2(200) NOT NULL,
	RESUME_NO varchar2(10) NOT NULL UNIQUE,
	PRIMARY KEY (CR_NUM)
);


CREATE TABLE COMMON
(
	COMMON_COD_NUM number(10) NOT NULL,
	COMMON_TYPE varchar2(30) NOT NULL,
	COMMON_COD_NAME varchar2(60) NOT NULL,
	COMMON_TYPE_COD varchar2(10) NOT NULL,
	PRIMARY KEY (COMMON_COD_NUM)
);


CREATE TABLE COMPANY
(
	COM_ID varchar2(20) NOT NULL,
	COM_PASSWORD varchar2(30) NOT NULL,
	COM_REGNO number(15) NOT NULL,
	COM_NAME varchar2(50) NOT NULL,
	COM_MAIL varchar2(50) NOT NULL,
	COM_ADD varchar2(500) NOT NULL,
	COM_TEL varchar2(15) NOT NULL,
	COM_CEO varchar2(15) NOT NULL,
	COM_AUTH number(1) NOT NULL,
	PRIMARY KEY (COM_ID)
);


CREATE TABLE GUIDE
(
	GUIDE_NO number(1) NOT NULL,
	GUIDE_TITLE varchar2(30) NOT NULL,
	GUIDE_CONTENT varchar2(3000) NOT NULL,
	MAN_ID varchar2(20) NOT NULL,
	PRIMARY KEY (GUIDE_NO)
);


CREATE TABLE HIRE
(
	HIRE_NO number(5) NOT NULL,
	HIRE_ID varchar2(20) NOT NULL,
	HIRE_AGE number(3) NOT NULL,
	HIRE_ADD varchar2(300) NOT NULL,
	HIRE_SECTOR varchar2(30) NOT NULL,
	HIRE_DAY varchar2(50) NOT NULL,
	HIRE_TIME varchar2(30) NOT NULL,
	HIRE_EMP varchar2(10) NOT NULL,
	HIRE_AL_DATE varchar2(50) NOT NULL,
	HIRE_COST number(10) NOT NULL,
	HIRE_SEXDTN number(1) NOT NULL,
	HIRE_NUM number(4) NOT NULL,
	HIRE_EDU1 varchar2(50) NOT NULL,
	HIRE_TYPE varchar2(10) NOT NULL,
	HIRE_EDU2 varchar2(10) NOT NULL,
	HIRE_COST_TYPE varchar2(15) NOT NULL,
	HIRE_DATE date,
	HIRE_TITLE varchar2(100),
	PRIMARY KEY (HIRE_NO)
);


CREATE TABLE HIRE_RESUME
(
	RESUME_NO varchar2(10) NOT NULL UNIQUE,
	HIRE_NO number(5) NOT NULL
);


CREATE TABLE MANAGER
(
	MAN_ID varchar2(20) NOT NULL,
	MAN_PASSWORD varchar2(30) NOT NULL,
	MAN_NAME varchar2(20) NOT NULL,
	MAN_AUTH number(1) NOT NULL,
	PRIMARY KEY (MAN_ID)
);


CREATE TABLE NOTICE
(
	NOTICE_NO number(5) NOT NULL,
	NOTICE_TITLE varchar2(30) NOT NULL,
	NOTICE_CONTENT varchar2(3000) NOT NULL,
	NOTICE_DATE date NOT NULL,
	MAN_ID varchar2(20) NOT NULL,
	PRIMARY KEY (NOTICE_NO)
);


CREATE TABLE QAALBABOARD
(
	QA_AL_NUM number(5) NOT NULL,
	QA_AL_TITLE varchar2(100),
	QA_AL_CONTENT varchar2(3000),
	QA_AL_DATE date,
	AL_MAN_CONTENT varchar2(3000),
	AL_MAN_DATE date,
	ALBA_ID varchar2(20) NOT NULL UNIQUE,
	MAN_ID varchar2(20) NOT NULL,
	PRIMARY KEY (QA_AL_NUM)
);


CREATE TABLE QACOMBOARD
(
	QA_COM_NUM number(5) NOT NULL,
	QA_COM_TITLE varchar2(100) NOT NULL,
	QA_COM_CONTENT varchar2(3000) NOT NULL,
	QA_COM_DATE date NOT NULL,
	QA_COM_ID varchar2(20) NOT NULL,
	MAN_ID varchar2(20) NOT NULL,
	COM_MAN_CONTENT varchar2(3000),
	COM_MAN_DATE date,
	PRIMARY KEY (QA_COM_NUM)
);


CREATE TABLE RESUME
(
	RESUME_NO varchar2(10) NOT NULL,
	ALBA_ID varchar2(20) NOT NULL,
	RESUME_EDU1 varchar2(20) NOT NULL,
	RESUME_EDU2 varchar2(10) NOT NULL,
	-- 신입OR 경력
	RESUME_CR1 varchar2(10) NOT NULL,
	RESUME_INTRCN varchar2(3000) NOT NULL,
	RESUME_ADD varchar2(100) NOT NULL,
	RESUME_SECTOR varchar2(30) NOT NULL,
	-- 알바/정규직/계약직
	RESUME_TYPE varchar2(10) NOT NULL,
	RESUME_DATE varchar2(30) NOT NULL,
	RESUME_TIME varchar2(30) NOT NULL,
	RESUME_OPENTERM number(3) NOT NULL,
	RESUME_DAY varchar2(50) NOT NULL,
	PRIMARY KEY (RESUME_NO)
);


CREATE TABLE RESUME_HIRE
(
	HIRE_NO number(5) NOT NULL,
	RL_NO number(5) NOT NULL
);


CREATE TABLE RESUME_LIST
(
	RESUME_NO varchar2(10) NOT NULL,
	RL_TITLE varchar2(100) NOT NULL,
	RL_DATE date NOT NULL,
	RL_NO number(5) NOT NULL,
	PRIMARY KEY (RL_NO)
);



/* Create Foreign Keys */

ALTER TABLE QAALBABOARD
	ADD FOREIGN KEY (ALBA_ID)
	REFERENCES ALBA (ALBA_ID)
;


ALTER TABLE RESUME
	ADD FOREIGN KEY (ALBA_ID)
	REFERENCES ALBA (ALBA_ID)
;


ALTER TABLE HIRE
	ADD FOREIGN KEY (HIRE_ID)
	REFERENCES COMPANY (COM_ID)
;


ALTER TABLE QACOMBOARD
	ADD FOREIGN KEY (QA_COM_ID)
	REFERENCES COMPANY (COM_ID)
;


ALTER TABLE HIRE_RESUME
	ADD FOREIGN KEY (HIRE_NO)
	REFERENCES HIRE (HIRE_NO)
;


ALTER TABLE RESUME_HIRE
	ADD FOREIGN KEY (HIRE_NO)
	REFERENCES HIRE (HIRE_NO)
;


ALTER TABLE GUIDE
	ADD FOREIGN KEY (MAN_ID)
	REFERENCES MANAGER (MAN_ID)
;


ALTER TABLE NOTICE
	ADD FOREIGN KEY (MAN_ID)
	REFERENCES MANAGER (MAN_ID)
;


ALTER TABLE QAALBABOARD
	ADD FOREIGN KEY (MAN_ID)
	REFERENCES MANAGER (MAN_ID)
;


ALTER TABLE QACOMBOARD
	ADD FOREIGN KEY (MAN_ID)
	REFERENCES MANAGER (MAN_ID)
;


ALTER TABLE CAREER
	ADD FOREIGN KEY (RESUME_NO)
	REFERENCES RESUME (RESUME_NO)
;


ALTER TABLE HIRE_RESUME
	ADD FOREIGN KEY (RESUME_NO)
	REFERENCES RESUME (RESUME_NO)
;


ALTER TABLE RESUME_LIST
	ADD FOREIGN KEY (RESUME_NO)
	REFERENCES RESUME (RESUME_NO)
;


ALTER TABLE RESUME_HIRE
	ADD FOREIGN KEY (RL_NO)
	REFERENCES RESUME_LIST (RL_NO)
;



/* Comments */

COMMENT ON COLUMN RESUME.RESUME_CR1 IS '신입OR 경력';
COMMENT ON COLUMN RESUME.RESUME_TYPE IS '알바/정규직/계약직';



